# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in billing-platform.gemspec
gemspec

group :development, :test do
  gem "rake", "~> 13.0"
  gem "rspec", "~> 3.12"
  gem "rubocop", "~> 1.50"
  gem "yard", "~> 0.9"
end

group :test do
  gem "webmock", "~> 3.18"
  gem "vcr", "~> 6.1"
  gem "simplecov", "~> 0.22"
end